run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  gocyclo:
    min-complexity: 10
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
      - errcheck
      - maintidx
      
  govet:
    shadow: true

  maintidx:
    under: 100


linters:
  disable-all: true
  enable:
   # - goimports
   # - staticcheck
   # - gocyclo
    - maintidx
   # - errcheck
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
