
FROM golang:1.25-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git ca-certificates

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/main ./cmd/app

FROM golang:1.25-alpine AS test-runner

WORKDIR /app

COPY --from=builder /app/main /app/main

COPY --from=builder /app ./

