// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "github.com/humanbelnik/kinoswap/core/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// EmbeddingReducer is an autogenerated mock type for the EmbeddingReducer type
type EmbeddingReducer struct {
	mock.Mock
}

// Reduce provides a mock function with given fields: ems
func (_m *EmbeddingReducer) Reduce(ems []*model.Embedding) model.Embedding {
	ret := _m.Called(ems)

	if len(ret) == 0 {
		panic("no return value specified for Reduce")
	}

	var r0 model.Embedding
	if rf, ok := ret.Get(0).(func([]*model.Embedding) model.Embedding); ok {
		r0 = rf(ems)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Embedding)
		}
	}

	return r0
}

// NewEmbeddingReducer creates a new instance of EmbeddingReducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmbeddingReducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmbeddingReducer {
	mock := &EmbeddingReducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
