// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/humanbelnik/kinoswap/core/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MetaRepository is an autogenerated mock type for the MetaRepository type
type MetaRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ectx, id
func (_m *MetaRepository) Delete(ectx context.Context, id uuid.UUID) error {
	ret := _m.Called(ectx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ectx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: ctx, id
func (_m *MetaRepository) Exists(ctx context.Context, id uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadAll provides a mock function with given fields: ctx
func (_m *MetaRepository) LoadAll(ctx context.Context) ([]*model.MovieMeta, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadAll")
	}

	var r0 []*model.MovieMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.MovieMeta, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.MovieMeta); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.MovieMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadSome provides a mock function with given fields: ctx, ids
func (_m *MetaRepository) LoadSome(ctx context.Context, ids []uuid.UUID) ([]*model.MovieMeta, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for LoadSome")
	}

	var r0 []*model.MovieMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]*model.MovieMeta, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []*model.MovieMeta); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.MovieMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, mm
func (_m *MetaRepository) Store(ctx context.Context, mm model.MovieMeta) error {
	ret := _m.Called(ctx, mm)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.MovieMeta) error); ok {
		r0 = rf(ctx, mm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StoreEmbedding provides a mock function with given fields: ctx, id, e
func (_m *MetaRepository) StoreEmbedding(ctx context.Context, id uuid.UUID, e model.Embedding) error {
	ret := _m.Called(ctx, id, e)

	if len(ret) == 0 {
		panic("no return value specified for StoreEmbedding")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.Embedding) error); ok {
		r0 = rf(ctx, id, e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMetaRepository creates a new instance of MetaRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetaRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetaRepository {
	mock := &MetaRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
