// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/humanbelnik/kinoswap/core/internal/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// PosterRepository is an autogenerated mock type for the PosterRepository type
type PosterRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, key
func (_m *PosterRepository) Delete(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GeneratePresignedURL provides a mock function with given fields: ctx, rawURL, ttl
func (_m *PosterRepository) GeneratePresignedURL(ctx context.Context, rawURL string, ttl time.Duration) (string, error) {
	ret := _m.Called(ctx, rawURL, ttl)

	if len(ret) == 0 {
		panic("no return value specified for GeneratePresignedURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) (string, error)); ok {
		return rf(ctx, rawURL, ttl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) string); ok {
		r0 = rf(ctx, rawURL, ttl)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = rf(ctx, rawURL, ttl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Load provides a mock function with given fields: ctx, key
func (_m *PosterRepository) Load(ctx context.Context, key string) (*model.Poster, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *model.Poster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Poster, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Poster); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Poster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, object, readyKey
func (_m *PosterRepository) Save(ctx context.Context, object *model.Poster, readyKey *string) (string, error) {
	ret := _m.Called(ctx, object, readyKey)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Poster, *string) (string, error)); ok {
		return rf(ctx, object, readyKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Poster, *string) string); ok {
		r0 = rf(ctx, object, readyKey)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Poster, *string) error); ok {
		r1 = rf(ctx, object, readyKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPosterRepository creates a new instance of PosterRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPosterRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PosterRepository {
	mock := &PosterRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
