// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/humanbelnik/kinoswap/core/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// VoteRepository is an autogenerated mock type for the VoteRepository type
type VoteRepository struct {
	mock.Mock
}

// AddReactions provides a mock function with given fields: ctx, roomID, userID, reactions
func (_m *VoteRepository) AddReactions(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, reactions map[uuid.UUID]int) error {
	ret := _m.Called(ctx, roomID, userID, reactions)

	if len(ret) == 0 {
		panic("no return value specified for AddReactions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, map[uuid.UUID]int) error); ok {
		r0 = rf(ctx, roomID, userID, reactions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsAllReady provides a mock function with given fields: ctx, roomID
func (_m *VoteRepository) IsAllReady(ctx context.Context, roomID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for IsAllReady")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = rf(ctx, roomID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParticipantsEmbeddings provides a mock function with given fields: ctx, roomID
func (_m *VoteRepository) ParticipantsEmbeddings(ctx context.Context, roomID uuid.UUID) ([]model.Embedding, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for ParticipantsEmbeddings")
	}

	var r0 []model.Embedding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.Embedding, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.Embedding); ok {
		r0 = rf(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Embedding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Results provides a mock function with given fields: ctx, roomID
func (_m *VoteRepository) Results(ctx context.Context, roomID uuid.UUID) ([]*model.Result, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for Results")
	}

	var r0 []*model.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.Result, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.Result); ok {
		r0 = rf(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RoomIDByCode provides a mock function with given fields: ctx, code
func (_m *VoteRepository) RoomIDByCode(ctx context.Context, code string) (uuid.UUID, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for RoomIDByCode")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (uuid.UUID, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) uuid.UUID); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SimilarMovies provides a mock function with given fields: ctx, queryEmbedding, limit
func (_m *VoteRepository) SimilarMovies(ctx context.Context, queryEmbedding []float32, limit int) ([]*model.MovieMeta, error) {
	ret := _m.Called(ctx, queryEmbedding, limit)

	if len(ret) == 0 {
		panic("no return value specified for SimilarMovies")
	}

	var r0 []*model.MovieMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []float32, int) ([]*model.MovieMeta, error)); ok {
		return rf(ctx, queryEmbedding, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []float32, int) []*model.MovieMeta); ok {
		r0 = rf(ctx, queryEmbedding, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.MovieMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []float32, int) error); ok {
		r1 = rf(ctx, queryEmbedding, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVoteRepository creates a new instance of VoteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVoteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VoteRepository {
	mock := &VoteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
