# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/proto/embedder.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api/proto/embedder.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61pi/proto/embedder.proto\x12\tembedding\"f\n\x15MovieEmbeddingRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06genres\x18\x02 \x03(\t\x12\x10\n\x08overview\x18\x03 \x01(\t\x12\x0c\n\x04year\x18\x04 \x01(\x05\x12\x0e\n\x06rating\x18\x05 \x01(\x02\"*\n\x1aPreferenceEmbeddingRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"&\n\x11\x45mbeddingResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\x32\xd0\x01\n\x10\x45mbeddingService\x12X\n\x14\x43reateMovieEmbedding\x12 .embedding.MovieEmbeddingRequest\x1a\x1c.embedding.EmbeddingResponse\"\x00\x12\x62\n\x19\x43reatePreferenceEmbedding\x12%.embedding.PreferenceEmbeddingRequest\x1a\x1c.embedding.EmbeddingResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.proto.embedder_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOVIEEMBEDDINGREQUEST']._serialized_start=39
  _globals['_MOVIEEMBEDDINGREQUEST']._serialized_end=141
  _globals['_PREFERENCEEMBEDDINGREQUEST']._serialized_start=143
  _globals['_PREFERENCEEMBEDDINGREQUEST']._serialized_end=185
  _globals['_EMBEDDINGRESPONSE']._serialized_start=187
  _globals['_EMBEDDINGRESPONSE']._serialized_end=225
  _globals['_EMBEDDINGSERVICE']._serialized_start=228
  _globals['_EMBEDDINGSERVICE']._serialized_end=436
# @@protoc_insertion_point(module_scope)
