// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/humanbelnik/kinoswap/core/internal/model"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// RoomRepository is an autogenerated mock type for the RoomRepository type
type RoomRepository struct {
	mock.Mock
}

// AddPreferenceEmbedding provides a mock function with given fields: ctx, code, userID, prefEmbedding
func (_m *RoomRepository) AddPreferenceEmbedding(ctx context.Context, code string, userID uuid.UUID, prefEmbedding model.Embedding) error {
	ret := _m.Called(ctx, code, userID, prefEmbedding)

	if len(ret) == 0 {
		panic("no return value specified for AddPreferenceEmbedding")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, model.Embedding) error); ok {
		r0 = rf(ctx, code, userID, prefEmbedding)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CleanupOrphantRooms provides a mock function with given fields: ctx, lobbiesDeadline, votingDeadline
func (_m *RoomRepository) CleanupOrphantRooms(ctx context.Context, lobbiesDeadline time.Duration, votingDeadline time.Duration) error {
	ret := _m.Called(ctx, lobbiesDeadline, votingDeadline)

	if len(ret) == 0 {
		panic("no return value specified for CleanupOrphantRooms")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration, time.Duration) error); ok {
		r0 = rf(ctx, lobbiesDeadline, votingDeadline)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateAndBook provides a mock function with given fields: ctx, room, ownerID
func (_m *RoomRepository) CreateAndBook(ctx context.Context, room model.Room, ownerID uuid.UUID) error {
	ret := _m.Called(ctx, room, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for CreateAndBook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Room, uuid.UUID) error); ok {
		r0 = rf(ctx, room, ownerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByCode provides a mock function with given fields: ctx, code
func (_m *RoomRepository) DeleteByCode(ctx context.Context, code string) error {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsOwner provides a mock function with given fields: ctx, code, ownerID
func (_m *RoomRepository) IsOwner(ctx context.Context, code string, ownerID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, code, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for IsOwner")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) (bool, error)); ok {
		return rf(ctx, code, ownerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) bool); ok {
		r0 = rf(ctx, code, ownerID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = rf(ctx, code, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsParticipant provides a mock function with given fields: ctx, code, userID
func (_m *RoomRepository) IsParticipant(ctx context.Context, code string, userID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, code, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsParticipant")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) (bool, error)); ok {
		return rf(ctx, code, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) bool); ok {
		r0 = rf(ctx, code, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = rf(ctx, code, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParticipantsCount provides a mock function with given fields: ctx, code
func (_m *RoomRepository) ParticipantsCount(ctx context.Context, code string) (int, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for ParticipantsCount")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetStatusByCode provides a mock function with given fields: ctx, code, status
func (_m *RoomRepository) SetStatusByCode(ctx context.Context, code string, status string) error {
	ret := _m.Called(ctx, code, status)

	if len(ret) == 0 {
		panic("no return value specified for SetStatusByCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, code, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StatusByCode provides a mock function with given fields: ctx, code
func (_m *RoomRepository) StatusByCode(ctx context.Context, code string) (string, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for StatusByCode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UUIDByCode provides a mock function with given fields: ctx, code
func (_m *RoomRepository) UUIDByCode(ctx context.Context, code string) (uuid.UUID, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for UUIDByCode")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (uuid.UUID, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) uuid.UUID); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRoomRepository creates a new instance of RoomRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoomRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoomRepository {
	mock := &RoomRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
